FROM node:12.16

RUN npm install create-react-app --global
RUN curl -o- -L https://yarnpkg.com/install.sh | bash

COPY ./website/ui/docker-entrypoint.sh /

EXPOSE 3000

WORKDIR /app/

CMD ["/docker-entrypoint.sh"]

