# multi-stage build

FROM node:8.9.4

RUN mkdir -p /app/
COPY website/ui /app/
COPY config/production.json /app/config.json
COPY config/production.json /app/src/config.json

WORKDIR /app/

RUN yarn
ARG publicurl
RUN PUBLIC_URL=$publicurl yarn build

# for final image

FROM nginx:1.13-alpine

RUN mkdir -p /app/
COPY  --from=0 /app/build /usr/share/nginx/html
COPY api/assets /usr/share/nginx/html/assets
COPY --from=0 /app/nginx.conf /etc/nginx/nginx.conf
