#!/usr/bin/env python

CtToTissuesKnown = {
"A172 immortalized cell line" : "brain",
"A172" : "brain" ,
"A172_immortalized_cell_line" : "brain",
"A375 immortalized cell line" : "skin",
"A375" : "skin" ,
"A375_immortalized_cell_line" : "skin",
"Caki2 immortalized cell line" : "kidney",
"Caki2" : "kidney" ,
"Caki2_immortalized_cell_line" : "kidney",
"Daoy immortalized cell line" : "brain",
"Daoy" : "brain" ,
"Daoy_immortalized_cell_line" : "brain",
"G401 immortalized cell line" : "kidney",
"G401" : "kidney" ,
"G401_immortalized_cell_line" : "kidney",
"GM12878 immortalized cell line" : "blood",
"GM12878" : "blood" ,
"GM12878_immortalized_cell_line" : "blood",
"H4 immortalized cell line" : "brain",
"H4" : "brain" ,
"H4_immortalized_cell_line" : "brain",
"H7-hESC stem cell" : "ESC",
"H7-hESC" : "ESC" ,
"H7-hESC_stem_cell" : "ESC",
"HT-29 immortalized cell line" : "intestine",
"HT-29" : "intestine" ,
"HT-29_immortalized_cell_line" : "intestine",
"HT1080 immortalized cell line" : "connective tissue",
"HT1080" : "connective tissue" ,
"HT1080_immortalized_cell_line" : "connective tissue",
"HepG2 immortalized cell line" : "liver",
"HepG2" : "liver" ,
"HepG2_immortalized_cell_line" : "liver",
"IMR-90 primary cell" : "lung",
"IMR-90_primary_cell" : "lung",
"K562 immortalized cell line" : "blood",
"K562" : "blood" ,
"K562_immortalized_cell_line" : "blood",
"Karpas-422 immortalized cell line" : "blood",
"Karpas-422" : "blood" ,
"Karpas-422_immortalized_cell_line" : "blood",
"LHCN-M2 immortalized cell line" : "muscle",
"LHCN-M2 in vitro differentiated cells" : "muscle",
"LHCN-M2" : "muscle" ,
"LHCN-M2_immortalized_cell_line" : "muscle",
"LHCN-M2_in_vitro_differentiated_cells" : "muscle",
"M059J immortalized cell line" : "brain",
"M059J" : "brain" ,
"M059J_immortalized_cell_line" : "brain",
"MCF-7 immortalized cell line" : "breast",
"MCF-7" : "breast" ,
"MCF-7_immortalized_cell_line" : "breast",
"MG63 immortalized cell line" : "bone",
"MG63" : "  bone" ,
"MG63_immortalized_cell_line" : "bone",
"NCI-H460 immortalized cell line" : "lung",
"NCI-H460" : "lung" ,
"NCI-H460_immortalized_cell_line" : "lung",
"OCI-LY7 immortalized cell line" : "blood",
"OCI-LY7" : "  blood" ,
"OCI-LY7_immortalized_cell_line" : "blood",
"PC-3 immortalized cell line" : "prostate",
"PC-3" : " prostate" ,
"PC-3_immortalized_cell_line" : "prostate",
"Peyer's patch tissue" : "lymphoid",
"Peyer's patch" : "lymphoid" ,
"Peyer's_patch_tissue" : "lymphoid",
"Purkinje cell primary cell" : "brain",
"Purkinje_cell_primary_cell" : "brain",
"RPMI-7951 immortalized cell line" : "skin",
"RPMI-7951" : "skin" ,
"RPMI-7951_immortalized_cell_line" : "skin",
"SJCRH30 immortalized cell line" : "bone marrow",
"SJCRH30" : "bone marrow" ,
"SJCRH30_immortalized_cell_line" : "bone marrow",
"SJSA1 immortalized cell line" : "bone",
"SJSA1" : "bone" ,
"SJSA1_immortalized_cell_line" : "bone",
"SK-MEL-5 immortalized cell line" : "skin",
"SK-MEL-5" : "skin" ,
"SK-MEL-5_immortalized_cell_line" : "skin",
"SK-N-DZ immortalized cell line" : "brain",
"SK-N-DZ" : " brain" ,
"SK-N-DZ_immortalized_cell_line" : "brain",
"adrenal gland tissue" : "adrenal",
"adrenal_gland_tissue" : "adrenal",
"airway epithelial cell primary cell" : "lung",
"airway epithelial cell" : "lung" ,
"airway_epithelial_cell_primary_cell" : "lung",
"aortic smooth muscle cell primary cell" : "blood vessel",
"aortic_smooth_muscle_cell_primary_cell" : "blood vessel",
"articular chondrocyte of knee joint primary cell" : "cartilage",
"articular chondrocyte of knee joint" : "cartilage" ,
"articular_chondrocyte_of_knee_joint_primary_cell" : "cartilage",
"ascending aorta tissue" : "blood vessel",
"ascending_aorta_tissue" : "blood vessel",
"astrocyte primary cell" : "brain",
"astrocyte" : "brain" ,
"astrocyte_primary_cell" : "brain",
"bipolar spindle neuron in vitro differentiated cells" : "brain",
"bipolar spindle neuron" : "brain" ,
"bipolar_spindle_neuron_in_vitro_differentiated_cells" : "brain",
"bladder microvascular endothelial cell primary cell" : "bladder",
"bladder_microvascular_endothelial_cell_primary_cell" : "bladder",
"body of pancreas tissue" : "pancreas",
"body_of_pancreas_tissue" : "pancreas",
"breast epithelium tissue" : "breast",
"breast epithelium" : "breast" ,
"breast_epithelium_tissue" : "breast",
"bronchial epithelial cell primary cell" : "lung",
"bronchial smooth muscle cell primary cell" : "lung",
"bronchial_epithelial_cell_primary_cell" : "lung",
"bronchial_smooth_muscle_cell_primary_cell" : "lung",
"bronchus fibroblast of lung primary cell" : "lung",
"bronchus_fibroblast_of_lung_primary_cell" : "lung",
"camera-type eye tissue" : "eye",
"camera-type_eye_tissue" : "eye",
"cardiac atrium fibroblast primary cell" : "heart",
"cardiac muscle cell in vitro differentiated cells" : "heart",
"cardiac muscle cell" : "heart",
"cardiac myocyte" : "heart" ,
"cardiac ventricle fibroblast primary cell" : "heart",
"cardiac_atrium_fibroblast_primary_cell" : "heart",
"cardiac_muscle_cell_in_vitro_differentiated_cells" : "heart",
"cardiac_ventricle_fibroblast_primary_cell" : "heart",
"cerebellum tissue" : "brain",
"cerebellum_tissue" : "brain",
"dermis blood vessel endothelial cell primary cell" : "blood vessel",
"dermis lymphatic vessel endothelial cell primary cell" : "blood vessel",
"dermis microvascular lymphatic vessel endothelial cell primary cell" : "lymphatic",
"dermis_blood_vessel_endothelial_cell_primary_cell" : "blood vessel",
"dermis_lymphatic_vessel_endothelial_cell_primary_cell" : "blood vessel",
"dermis_microvascular_lymphatic_vessel_endothelial_cell_primary_cell" : "lymphatic",
"diencephalon tissue" : "brain",
"diencephalon_tissue" : "brain",
"endometrial microvascular endothelial cells primary cell" : "uterus",
"endometrial_microvascular_endothelial_cells_primary_cell" : "uterus",
"endothelial cell of coronary artery primary cell" : "blood vessel",
"endothelial_cell_of_coronary_artery_primary_cell" : "blood vessel",
"epithelial cell of alveolus of lung primary cell" : "lung",
"epithelial cell of proximal tubule primary cell" : "kidney",
"epithelial cell of umbilical artery primary cell" : "extraembryonic structure",
"epithelial_cell_of_alveolus_of_lung_primary_cell" : "lung",
"epithelial_cell_of_proximal_tubule_primary_cell" : "kidney",
"epithelial_cell_of_umbilical_artery_primary_cell" : "extraembryonic structure",
"esophagus muscularis mucosa tissue" : "esophagus",
"esophagus squamous epithelium tissue" : "esophagus",
"esophagus_muscularis_mucosa_tissue" : "esophagus",
"esophagus_squamous_epithelium_tissue" : "esophagus",
"fibroblast of arm primary cell" : "skin",
"fibroblast of dermis primary cell" : "skin",
"fibroblast of lung primary cell" : "lung",
"fibroblast of the aortic adventitia primary cell" : "blood vessel",
"fibroblast of villous mesenchyme primary cell" : "extraembryonic structure",
"fibroblast_of_arm_primary_cell" : "skin",
"fibroblast_of_dermis_primary_cell" : "skin",
"fibroblast_of_lung_primary_cell" : "lung",
"fibroblast_of_the_aortic_adventitia_primary_cell" : "blood vessel",
"fibroblast_of_villous_mesenchyme_primary_cell" : "extraembryonic structure",
"frontal cortex tissue" : "brain",
"frontal_cortex_tissue" : "brain",
"gastrocnemius medialis tissue" : "muscle",
"gastrocnemius_medialis_tissue" : "muscle",
"gastroesophageal sphincter tissue" : "esophagus",
"gastroesophageal_sphincter_tissue" : "esophagus",
"glomerular endothelial cell primary cell" : "kidney",
"glomerular_endothelial_cell_primary_cell" : "kidney",
"hair follicle dermal papilla cell primary cell" : "skin",
"hair follicular keratinocyte primary cell" : "skin",
"hair_follicle_dermal_papilla_cell_primary_cell" : "skin",
"hair_follicular_keratinocyte_primary_cell" : "skin",
"heart left ventricle tissue" : "heart",
"heart tissue" : "heart",
"heart_left_ventricle_tissue" : "heart",
"heart_tissue" : "heart",
"hematopoietic multipotent progenitor cell primary cell" : "blood",
"hematopoietic multipotent progenitor cell" : "blood" ,
"hematopoietic_multipotent_progenitor_cell_primary_cell" : "blood",
"hepatocyte in vitro differentiated cells" : "liver",
"hepatocyte_in_vitro_differentiated_cells" : "liver",
"induced pluripotent stem cell induced pluripotent stem cell line" : "ESC",
"induced pluripotent stem cell" : "iPSC" ,
"induced_pluripotent_stem_cell_induced_pluripotent_stem_cell_line" : "ESC",
"kidney epithelial cell primary cell" : "kidney",
"kidney_epithelial_cell_primary_cell" : "kidney",
"liver tissue" : "liver",
"liver_tissue" : "liver",
"lower leg skin tissue" : "skin",
"lower_leg_skin_tissue" : "skin",
"lung microvascular endothelial cell primary cell" : "lung",
"lung tissue" : "lung",
"lung_microvascular_endothelial_cell_primary_cell" : "lung",
"lung_tissue" : "lung",
"mammary epithelial cell primary cell" : "breast",
"mammary microvascular endothelial cell primary cell" : "breast",
"mammary_epithelial_cell_primary_cell" : "breast",
"mammary_microvascular_endothelial_cell_primary_cell" : "breast",
"melanocyte of skin primary cell" : "skin",
"melanocyte_of_skin_primary_cell" : "skin",
"mesangial cell primary cell" : "kidney",
"mesangial cell" : "kidney" ,
"mesangial_cell_primary_cell" : "kidney",
"mesenchymal stem cell of Wharton's jelly stem cell" : "ESC derived",
"mesenchymal stem cell of adipose stem cell" : "ESC derived",
"mesenchymal stem cell of the bone marrow stem cell" : "ESC derived",
"mesenchymal_stem_cell_of_Wharton's_jelly_stem_cell" : "ESC derived",
"mesenchymal_stem_cell_of_adipose_stem_cell" : "ESC derived",
"mesenchymal_stem_cell_of_the_bone_marrow_stem_cell" : "ESC derived",
"metanephros tissue" : "embryonic structure",
"metanephros_tissue" : "embryonic structure",
"mononuclear cell primary cell" : "blood",
"mononuclear_cell_primary_cell" : "blood",
"myometrial cell primary cell" : "uterus",
"myometrial cell" : "myometrium" ,
"myometrial_cell_primary_cell" : "uterus",
"myotube in vitro differentiated cells" : "muscle",
"myotube_in_vitro_differentiated_cells" : "muscle",
"nasal cavity respiratory epithelium epithelial cell of viscerocranial mucosa primary cell" : "lung",
"nasal_cavity_respiratory_epithelium_epithelial_cell_of_viscerocranial_mucosa_primary_cell" : "lung",
"neural progenitor cell in vitro differentiated cells" : "brain",
"neural progenitor cell" : "brain" ,
"neural_progenitor_cell_in_vitro_differentiated_cells" : "brain",
"occipital lobe tissue" : "brain",
"occipital lobe" : "  brain" ,
"occipital_lobe_tissue" : "brain",
"omental fat pad tissue" : "fat",
"omental fat pad" : "fat" ,
"omental_fat_pad_tissue" : "fat",
"osteoblast primary cell" : "bone marrow",
"osteoblast" : "bone" ,
"osteoblast_primary_cell" : "bone marrow",
"ovary tissue" : "ovary",
"ovary_tissue" : "ovary",
"parietal lobe tissue" : "brain",
"parietal lobe" : "brain" ,
"parietal_lobe_tissue" : "brain",
"pericardium fibroblast primary cell" : "heart",
"pericardium fibroblast" : "heart" ,
"pericardium_fibroblast_primary_cell" : "heart",
"pericyte cell primary cell" : "blood vessel",
"pericyte cell" : "blood vessel" ,
"pericyte_cell_primary_cell" : "blood vessel",
"placental epithelial cell primary cell" : "placenta",
"placental_epithelial_cell_primary_cell" : "placenta",
"prostate gland tissue" : "prostate",
"prostate_gland_tissue" : "prostate",
"pulmonary artery endothelial cell primary cell" : "blood vessel",
"pulmonary_artery_endothelial_cell_primary_cell" : "blood vessel",
"regular cardiac myocyte primary cell" : "heart",
"regular cardiac myocyte" : "heart" ,
"regular_cardiac_myocyte_primary_cell" : "heart",
"renal cortical epithelial cell primary cell" : "kidney",
"renal_cortical_epithelial_cell_primary_cell" : "kidney",
"right atrium auricular region tissue" : "heart",
"right lobe of liver tissue" : "liver",
"right_atrium_auricular_region_tissue" : "heart",
"right_lobe_of_liver_tissue" : "liver",
"sigmoid colon tissue" : "intestine",
"sigmoid_colon_tissue" : "intestine",
"skeletal muscle myoblast primary cell" : "muscle",
"skeletal muscle myoblast" : "muscle" ,
"skeletal muscle satellite cell primary cell" : "muscle",
"skeletal muscle tissue tissue" : "muscle",
"skeletal_muscle_myoblast_primary_cell" : "muscle",
"skeletal_muscle_satellite_cell_primary_cell" : "muscle",
"skeletal_muscle_tissue_tissue" : "muscle",
"skin of body tissue" : "skin",
"skin_of_body_tissue" : "skin",
"smooth muscle cell in vitro differentiated cells" : "muscle",
"smooth muscle cell of bladder primary cell" : "bladder",
"smooth muscle cell of the coronary artery primary cell" : "blood vessel",
"smooth muscle cell of the pulmonary artery primary cell" : "blood vessel",
"smooth muscle cell of the umbilical artery primary cell" : "extraembryonic structure",
"smooth muscle cell of trachea primary cell" : "lung",
"smooth muscle cell" : "muscle" ,
"smooth_muscle_cell_in_vitro_differentiated_cells" : "muscle",
"smooth_muscle_cell_of_bladder_primary_cell" : "bladder",
"smooth_muscle_cell_of_the_coronary_artery_primary_cell" : "blood vessel",
"smooth_muscle_cell_of_the_pulmonary_artery_primary_cell" : "blood vessel",
"smooth_muscle_cell_of_the_umbilical_artery_primary_cell" : "extraembryonic structure",
"smooth_muscle_cell_of_trachea_primary_cell" : "lung",
"spinal cord tissue" : "spinal cord",
"spinal_cord_tissue" : "spinal cord",
"spleen tissue" : "spleen",
"spleen_tissue" : "spleen",
"stomach tissue" : "stomach",
"stomach_tissue" : "stomach",
"subcutaneous adipose tissue tissue" : "fat",
"subcutaneous adipose tissue" : "fat" ,
"subcutaneous preadipocyte primary cell" : "fat",
"subcutaneous preadipocyte" : "fat" ,
"subcutaneous_adipose_tissue_tissue" : "fat",
"subcutaneous_preadipocyte_primary_cell" : "fat",
"suprapubic skin tissue" : "skin",
"suprapubic skin" : "skin" ,
"suprapubic_skin_tissue" : "skin",
"temporal lobe tissue" : "brain",
"temporal lobe" : "brain" ,
"temporal_lobe_tissue" : "brain",
"testis tissue" : "testis",
"testis_tissue" : "testis",
"thoracic aorta endothelial cell primary cell" : "blood vessel",
"thoracic aorta tissue" : "blood vessel",
"thoracic_aorta_endothelial_cell_primary_cell" : "blood vessel",
"thoracic_aorta_tissue" : "blood vessel",
"thyroid gland tissue" : "thyroid",
"thyroid_gland_tissue" : "thyroid",
"tibial nerve tissue" : "nervous system",
"tibial nerve" : "nervous system" ,
"tibial_nerve_tissue" : "nervous system",
"tongue tissue" : "tongue",
"tongue_tissue" : "tongue",
"tracheal epithelial cell primary cell" : "trachea",
"tracheal_epithelial_cell_primary_cell" : "trachea",
"transverse colon tissue" : "intestine",
"transverse_colon_tissue" : "intestine",
"umbilical cord tissue" : "umbilical cord",
"umbilical_cord_tissue" : "umbilical_cord",
"upper lobe of left lung tissue" : "lung",
"upper_lobe_of_left_lung_tissue" : "lung",
"urinary bladder tissue" : "bladder",
"urinary_bladder_tissue" : "bladder",
"uterine smooth muscle cell primary cell" : "uterus",
"uterine smooth muscle cell" : "uterus" ,
"uterine_smooth_muscle_cell_primary_cell" : "uterus",
"uterus tissue" : "uterus",
"uterus" : "uterus" ,
"uterus_tissue" : "uterus",
"vagina tissue" : "vagina",
"vagina" : "vagina" ,
"vagina_tissue" : "vagina",
"vein endothelial cell primary cell" : "blood vessel",
"vein_endothelial_cell_primary_cell" : "blood vessel"
}

def CtToTissue(ct):
    if ct in CtToTissuesKnown:
        return CtToTissuesKnown[ct]
    return ""

