approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

nodeLinker: node-modules

packageExtensions:
  react-scripts@*:
    dependencies:
      "@babel/runtime": "7.24.0"

yarnPath: .yarn/releases/yarn-4.14.1.cjs
