jest.mock('../../src/db/db');

import { db } from '../../src/db/db';
import * as db_geneexp from '../../src/db/db_geneexp';

describe('db_geneexp', () => {
    const data_expression = [
        {
            ensemblid_ver: 'ENSG00000187514.10',
            gene_name: 'PTMA',
            expid: 'ENCSR236OON',
            organ: 'adipose tissue',
            celltype: 'adipose tissue',
            agetitle: '',
            reps: [{ tpm: 551.84, replicate: 1, fpkm: 577.69 }],
        },
        {
            ensemblid_ver: 'ENSG00000187514.10',
            gene_name: 'PTMA',
            expid: 'ENCSR686JJB',
            organ: 'adipose tissue',
            celltype: 'adipose tissue',
            agetitle: '',
            reps: [{ tpm: 965.87, replicate: 1, fpkm: 890.55 }],
        },
        {
            ensemblid_ver: 'ENSG00000187514.10',
            gene_name: 'PTMA',
            expid: 'ENCSR718CDN',
            organ: 'adipose tissue',
            celltype: 'adipose tissue',
            agetitle: '',
            reps: [{ tpm: 1144.68, replicate: 1, fpkm: 1252.83 }],
        },
        {
            ensemblid_ver: 'ENSG00000187514.10',
            gene_name: 'PTMA',
            expid: 'ENCSR741QEH',
            organ: 'adipose tissue',
            celltype: 'adipose tissue',
            agetitle: '',
            reps: [{ tpm: 119.98, replicate: 1, fpkm: 196.27 }],
        },
        {
            ensemblid_ver: 'ENSG00000187514.10',
            gene_name: 'PTMA',
            expid: 'ENCSR000AAT',
            organ: 'artery',
            celltype: 'epithelial cell of umbilical artery',
            agetitle: '',
            reps: [{ tpm: 33.41, replicate: 1, fpkm: 364.77 }, { tpm: 94.03, replicate: 2, fpkm: 695.29 }],
        },
        {
            ensemblid_ver: 'ENSG00000187514.10',
            gene_name: 'PTMA',
            expid: 'ENCSR000AAM',
            organ: 'artery',
            celltype: 'pulmonary artery endothelial cell',
            agetitle: '',
            reps: [{ tpm: 437.01, replicate: 1, fpkm: 706.52 }, { tpm: 191.69, replicate: 2, fpkm: 541.99 }],
        },
        {
            ensemblid_ver: 'ENSG00000187514.10',
            gene_name: 'PTMA',
            expid: 'ENCSR000AAG',
            organ: 'artery',
            celltype: 'smooth muscle cell of the coronary artery',
            agetitle: '',
            reps: [{ tpm: 81.67, replicate: 2, fpkm: 262.98 }, { tpm: 133.11, replicate: 1, fpkm: 534.02 }],
        },
        {
            ensemblid_ver: 'ENSG00000187514.10',
            gene_name: 'PTMA',
            expid: 'ENCSR000AAN',
            organ: 'artery',
            celltype: 'smooth muscle cell of the pulmonary artery',
            agetitle: '',
            reps: [{ tpm: 141.8, replicate: 1, fpkm: 176.35 }, { tpm: 62.33, replicate: 2, fpkm: 138.86 }],
        },
        {
            ensemblid_ver: 'ENSG00000187514.10',
            gene_name: 'PTMA',
            expid: 'ENCSR000AAU',
            organ: 'artery',
            celltype: 'smooth muscle cell of the umbilical artery',
            agetitle: '',
            reps: [{ tpm: 142.28, replicate: 2, fpkm: 250.02 }, { tpm: 15.09, replicate: 1, fpkm: 145.37 }],
        },
        {
            ensemblid_ver: 'ENSG00000187514.10',
            gene_name: 'PTMA',
            expid: 'ENCSR000COQ',
            organ: 'blood',
            celltype: 'GM12878',
            agetitle: '',
            reps: [{ tpm: 835.98, replicate: 2, fpkm: 675.35 }, { tpm: 1052.93, replicate: 1, fpkm: 813.93 }],
        },
        {
            ensemblid_ver: 'ENSG00000187514.10',
            gene_name: 'PTMA',
            expid: 'ENCSR000COR',
            organ: 'blood',
            celltype: 'GM12878',
            agetitle: '',
            reps: [{ tpm: 740.58, replicate: 2, fpkm: 993.8 }, { tpm: 501.1, replicate: 1, fpkm: 633.14 }],
        },
        {
            ensemblid_ver: 'ENSG00000187514.10',
            gene_name: 'PTMA',
            expid: 'ENCSR000CPO',
            organ: 'blood',
            celltype: 'GM12878',
            agetitle: '',
            reps: [{ tpm: 342.04, replicate: 1, fpkm: 280.57 }, { tpm: 843.76, replicate: 2, fpkm: 674.81 }],
        },
        {
            ensemblid_ver: 'ENSG00000187514.10',
            gene_name: 'PTMA',
            expid: 'ENCSR297UBP',
            organ: 'blood',
            celltype: 'GM12878',
            agetitle: '',
            reps: [{ tpm: 1793.09, replicate: 1, fpkm: 1761.07 }, { tpm: 1761.97, replicate: 2, fpkm: 1761.27 }],
        },
        {
            ensemblid_ver: 'ENSG00000187514.10',
            gene_name: 'PTMA',
            expid: 'ENCSR843RJV',
            organ: 'blood',
            celltype: 'GM12878',
            agetitle: '',
            reps: [{ tpm: 3073.92, replicate: 1, fpkm: 2452.22 }, { tpm: 2717.8, replicate: 2, fpkm: 2135.5 }],
        },
        {
            ensemblid_ver: 'ENSG00000187514.10',
            gene_name: 'PTMA',
            expid: 'ENCSR000CWJ',
            organ: 'blood',
            celltype: 'K562',
            agetitle: '',
            reps: [{ tpm: 870.57, replicate: 1, fpkm: 702.67 }],
        },
        {
            ensemblid_ver: 'ENSG00000187514.10',
            gene_name: 'PTMA',
            expid: 'ENCSR038WEK',
            organ: 'blood',
            celltype: 'K562',
            agetitle: '',
            reps: [{ tpm: 462.49, replicate: 2, fpkm: 982.86 }, { tpm: 591.3, replicate: 1, fpkm: 1092.77 }],
        },
        {
            ensemblid_ver: 'ENSG00000187514.10',
            gene_name: 'PTMA',
            expid: 'ENCSR040YBR',
            organ: 'blood',
            celltype: 'K562',
            agetitle: '',
            reps: [{ tpm: 161.95, replicate: 1, fpkm: 395.42 }, { tpm: 153.33, replicate: 2, fpkm: 380.57 }],
        },
        {
            ensemblid_ver: 'ENSG00000187514.10',
            gene_name: 'PTMA',
            expid: 'ENCSR109IQO',
            organ: 'blood',
            celltype: 'K562',
            agetitle: '',
            reps: [{ tpm: 510.64, replicate: 2, fpkm: 1165.55 }, { tpm: 528.26, replicate: 1, fpkm: 1157.82 }],
        },
        {
            ensemblid_ver: 'ENSG00000187514.10',
            gene_name: 'PTMA',
            expid: 'ENCSR384ZXD',
            organ: 'blood',
            celltype: 'K562',
            agetitle: '',
            reps: [{ tpm: 1806.29, replicate: 1, fpkm: 2245.66 }, { tpm: 1586.37, replicate: 2, fpkm: 2077.06 }],
        },
    ];
    const expression_result = [
        {
            tissue: 'adipose tissue',
            cellType: 'adipose tissue',
            expID: 'ENCSR236OON',
            ageTitle: '',
            gene_name: 'PTMA',
            ensemblid_ver: 'ENSG00000187514.10',
            reps: [
                {
                    replicate: 1,
                    rawTPM: 551.84,
                    logTPM: 9.11,
                    rawFPKM: 577.69,
                    logFPKM: 9.17,
                },
                {
                    replicate: 'mean',
                    rawTPM: 551.84,
                    logTPM: 9.11,
                    rawFPKM: 577.69,
                    logFPKM: 9.17,
                    rID: '',
                },
            ],
        },
        {
            tissue: 'adipose tissue',
            cellType: 'adipose tissue',
            expID: 'ENCSR686JJB',
            ageTitle: '',
            gene_name: 'PTMA',
            ensemblid_ver: 'ENSG00000187514.10',
            reps: [
                {
                    replicate: 1,
                    rawTPM: 965.87,
                    logTPM: 9.92,
                    rawFPKM: 890.55,
                    logFPKM: 9.8,
                },
                {
                    replicate: 'mean',
                    rawTPM: 965.87,
                    logTPM: 9.92,
                    rawFPKM: 890.55,
                    logFPKM: 9.8,
                    rID: '',
                },
            ],
        },
        {
            tissue: 'adipose tissue',
            cellType: 'adipose tissue',
            expID: 'ENCSR718CDN',
            ageTitle: '',
            gene_name: 'PTMA',
            ensemblid_ver: 'ENSG00000187514.10',
            reps: [
                {
                    replicate: 1,
                    rawTPM: 1144.68,
                    logTPM: 10.16,
                    rawFPKM: 1252.83,
                    logFPKM: 10.29,
                },
                {
                    replicate: 'mean',
                    rawTPM: 1144.68,
                    logTPM: 10.16,
                    rawFPKM: 1252.83,
                    logFPKM: 10.29,
                    rID: '',
                },
            ],
        },
        {
            tissue: 'adipose tissue',
            cellType: 'adipose tissue',
            expID: 'ENCSR741QEH',
            ageTitle: '',
            gene_name: 'PTMA',
            ensemblid_ver: 'ENSG00000187514.10',
            reps: [
                {
                    replicate: 1,
                    rawTPM: 119.98,
                    logTPM: 6.91,
                    rawFPKM: 196.27,
                    logFPKM: 7.62,
                },
                {
                    replicate: 'mean',
                    rawTPM: 119.98,
                    logTPM: 6.91,
                    rawFPKM: 196.27,
                    logFPKM: 7.62,
                    rID: '',
                },
            ],
        },
        {
            tissue: 'artery',
            cellType: 'epithelial cell of umbilical artery',
            expID: 'ENCSR000AAT',
            ageTitle: '',
            gene_name: 'PTMA',
            ensemblid_ver: 'ENSG00000187514.10',
            reps: [
                {
                    replicate: 1,
                    rawTPM: 33.41,
                    logTPM: 5.06,
                    rawFPKM: 364.77,
                    logFPKM: 8.51,
                },
                {
                    replicate: 2,
                    rawTPM: 94.03,
                    logTPM: 6.56,
                    rawFPKM: 695.29,
                    logFPKM: 9.44,
                },
                {
                    replicate: 'mean',
                    rawTPM: 63.72,
                    logTPM: 5.99,
                    rawFPKM: 530.03,
                    logFPKM: 9.05,
                    rID: ',',
                },
            ],
        },
        {
            tissue: 'artery',
            cellType: 'pulmonary artery endothelial cell',
            expID: 'ENCSR000AAM',
            ageTitle: '',
            gene_name: 'PTMA',
            ensemblid_ver: 'ENSG00000187514.10',
            reps: [
                {
                    replicate: 1,
                    rawTPM: 437.01,
                    logTPM: 8.77,
                    rawFPKM: 706.52,
                    logFPKM: 9.46,
                },
                {
                    replicate: 2,
                    rawTPM: 191.69,
                    logTPM: 7.58,
                    rawFPKM: 541.99,
                    logFPKM: 9.08,
                },
                {
                    replicate: 'mean',
                    rawTPM: 314.35,
                    logTPM: 8.3,
                    rawFPKM: 624.255,
                    logFPKM: 9.29,
                    rID: ',',
                },
            ],
        },
        {
            tissue: 'artery',
            cellType: 'smooth muscle cell of the coronary artery',
            expID: 'ENCSR000AAG',
            ageTitle: '',
            gene_name: 'PTMA',
            ensemblid_ver: 'ENSG00000187514.10',
            reps: [
                {
                    replicate: 2,
                    rawTPM: 81.67,
                    logTPM: 6.35,
                    rawFPKM: 262.98,
                    logFPKM: 8.04,
                },
                {
                    replicate: 1,
                    rawTPM: 133.11,
                    logTPM: 7.06,
                    rawFPKM: 534.02,
                    logFPKM: 9.06,
                },
                {
                    replicate: 'mean',
                    rawTPM: 107.39000000000001,
                    logTPM: 6.75,
                    rawFPKM: 398.5,
                    logFPKM: 8.64,
                    rID: ',',
                },
            ],
        },
        {
            tissue: 'artery',
            cellType: 'smooth muscle cell of the pulmonary artery',
            expID: 'ENCSR000AAN',
            ageTitle: '',
            gene_name: 'PTMA',
            ensemblid_ver: 'ENSG00000187514.10',
            reps: [
                {
                    replicate: 1,
                    rawTPM: 141.8,
                    logTPM: 7.15,
                    rawFPKM: 176.35,
                    logFPKM: 7.46,
                },
                {
                    replicate: 2,
                    rawTPM: 62.33,
                    logTPM: 5.96,
                    rawFPKM: 138.86,
                    logFPKM: 7.12,
                },
                {
                    replicate: 'mean',
                    rawTPM: 102.065,
                    logTPM: 6.67,
                    rawFPKM: 157.60500000000002,
                    logFPKM: 7.3,
                    rID: ',',
                },
            ],
        },
        {
            tissue: 'artery',
            cellType: 'smooth muscle cell of the umbilical artery',
            expID: 'ENCSR000AAU',
            ageTitle: '',
            gene_name: 'PTMA',
            ensemblid_ver: 'ENSG00000187514.10',
            reps: [
                {
                    replicate: 2,
                    rawTPM: 142.28,
                    logTPM: 7.15,
                    rawFPKM: 250.02,
                    logFPKM: 7.97,
                },
                {
                    replicate: 1,
                    rawTPM: 15.09,
                    logTPM: 3.92,
                    rawFPKM: 145.37,
                    logFPKM: 7.18,
                },
                {
                    replicate: 'mean',
                    rawTPM: 78.685,
                    logTPM: 6.3,
                    rawFPKM: 197.695,
                    logFPKM: 7.63,
                    rID: ',',
                },
            ],
        },
        {
            tissue: 'blood',
            cellType: 'GM12878',
            expID: 'ENCSR000COQ',
            ageTitle: '',
            gene_name: 'PTMA',
            ensemblid_ver: 'ENSG00000187514.10',
            reps: [
                {
                    replicate: 2,
                    rawTPM: 835.98,
                    logTPM: 9.71,
                    rawFPKM: 675.35,
                    logFPKM: 9.4,
                },
                {
                    replicate: 1,
                    rawTPM: 1052.93,
                    logTPM: 10.04,
                    rawFPKM: 813.93,
                    logFPKM: 9.67,
                },
                {
                    replicate: 'mean',
                    rawTPM: 944.455,
                    logTPM: 9.88,
                    rawFPKM: 744.64,
                    logFPKM: 9.54,
                    rID: ',',
                },
            ],
        },
        {
            tissue: 'blood',
            cellType: 'GM12878',
            expID: 'ENCSR000COR',
            ageTitle: '',
            gene_name: 'PTMA',
            ensemblid_ver: 'ENSG00000187514.10',
            reps: [
                {
                    replicate: 2,
                    rawTPM: 740.58,
                    logTPM: 9.53,
                    rawFPKM: 993.8,
                    logFPKM: 9.96,
                },
                {
                    replicate: 1,
                    rawTPM: 501.1,
                    logTPM: 8.97,
                    rawFPKM: 633.14,
                    logFPKM: 9.31,
                },
                {
                    replicate: 'mean',
                    rawTPM: 620.84,
                    logTPM: 9.28,
                    rawFPKM: 813.47,
                    logFPKM: 9.67,
                    rID: ',',
                },
            ],
        },
        {
            tissue: 'blood',
            cellType: 'GM12878',
            expID: 'ENCSR000CPO',
            ageTitle: '',
            gene_name: 'PTMA',
            ensemblid_ver: 'ENSG00000187514.10',
            reps: [
                {
                    replicate: 1,
                    rawTPM: 342.04,
                    logTPM: 8.42,
                    rawFPKM: 280.57,
                    logFPKM: 8.13,
                },
                {
                    replicate: 2,
                    rawTPM: 843.76,
                    logTPM: 9.72,
                    rawFPKM: 674.81,
                    logFPKM: 9.4,
                },
                {
                    replicate: 'mean',
                    rawTPM: 592.9,
                    logTPM: 9.21,
                    rawFPKM: 477.68999999999994,
                    logFPKM: 8.9,
                    rID: ',',
                },
            ],
        },
        {
            tissue: 'blood',
            cellType: 'GM12878',
            expID: 'ENCSR297UBP',
            ageTitle: '',
            gene_name: 'PTMA',
            ensemblid_ver: 'ENSG00000187514.10',
            reps: [
                {
                    replicate: 1,
                    rawTPM: 1793.09,
                    logTPM: 10.81,
                    rawFPKM: 1761.07,
                    logFPKM: 10.78,
                },
                {
                    replicate: 2,
                    rawTPM: 1761.97,
                    logTPM: 10.78,
                    rawFPKM: 1761.27,
                    logFPKM: 10.78,
                },
                {
                    replicate: 'mean',
                    rawTPM: 1777.53,
                    logTPM: 10.8,
                    rawFPKM: 1761.17,
                    logFPKM: 10.78,
                    rID: ',',
                },
            ],
        },
        {
            tissue: 'blood',
            cellType: 'GM12878',
            expID: 'ENCSR843RJV',
            ageTitle: '',
            gene_name: 'PTMA',
            ensemblid_ver: 'ENSG00000187514.10',
            reps: [
                {
                    replicate: 1,
                    rawTPM: 3073.92,
                    logTPM: 11.59,
                    rawFPKM: 2452.22,
                    logFPKM: 11.26,
                },
                {
                    replicate: 2,
                    rawTPM: 2717.8,
                    logTPM: 11.41,
                    rawFPKM: 2135.5,
                    logFPKM: 11.06,
                },
                {
                    replicate: 'mean',
                    rawTPM: 2895.86,
                    logTPM: 11.5,
                    rawFPKM: 2293.8599999999997,
                    logFPKM: 11.16,
                    rID: ',',
                },
            ],
        },
        {
            tissue: 'blood',
            cellType: 'K562',
            expID: 'ENCSR000CWJ',
            ageTitle: '',
            gene_name: 'PTMA',
            ensemblid_ver: 'ENSG00000187514.10',
            reps: [
                {
                    replicate: 1,
                    rawTPM: 870.57,
                    logTPM: 9.77,
                    rawFPKM: 702.67,
                    logFPKM: 9.46,
                },
                {
                    replicate: 'mean',
                    rawTPM: 870.57,
                    logTPM: 9.77,
                    rawFPKM: 702.67,
                    logFPKM: 9.46,
                    rID: '',
                },
            ],
        },
        {
            tissue: 'blood',
            cellType: 'K562',
            expID: 'ENCSR038WEK',
            ageTitle: '',
            gene_name: 'PTMA',
            ensemblid_ver: 'ENSG00000187514.10',
            reps: [
                {
                    replicate: 2,
                    rawTPM: 462.49,
                    logTPM: 8.85,
                    rawFPKM: 982.86,
                    logFPKM: 9.94,
                },
                {
                    replicate: 1,
                    rawTPM: 591.3,
                    logTPM: 9.21,
                    rawFPKM: 1092.77,
                    logFPKM: 10.09,
                },
                {
                    replicate: 'mean',
                    rawTPM: 526.895,
                    logTPM: 9.04,
                    rawFPKM: 1037.815,
                    logFPKM: 10.02,
                    rID: ',',
                },
            ],
        },
        {
            tissue: 'blood',
            cellType: 'K562',
            expID: 'ENCSR040YBR',
            ageTitle: '',
            gene_name: 'PTMA',
            ensemblid_ver: 'ENSG00000187514.10',
            reps: [
                {
                    replicate: 1,
                    rawTPM: 161.95,
                    logTPM: 7.34,
                    rawFPKM: 395.42,
                    logFPKM: 8.63,
                },
                {
                    replicate: 2,
                    rawTPM: 153.33,
                    logTPM: 7.26,
                    rawFPKM: 380.57,
                    logFPKM: 8.57,
                },
                {
                    replicate: 'mean',
                    rawTPM: 157.64,
                    logTPM: 7.3,
                    rawFPKM: 387.995,
                    logFPKM: 8.6,
                    rID: ',',
                },
            ],
        },
        {
            tissue: 'blood',
            cellType: 'K562',
            expID: 'ENCSR109IQO',
            ageTitle: '',
            gene_name: 'PTMA',
            ensemblid_ver: 'ENSG00000187514.10',
            reps: [
                {
                    replicate: 2,
                    rawTPM: 510.64,
                    logTPM: 9,
                    rawFPKM: 1165.55,
                    logFPKM: 10.19,
                },
                {
                    replicate: 1,
                    rawTPM: 528.26,
                    logTPM: 9.05,
                    rawFPKM: 1157.82,
                    logFPKM: 10.18,
                },
                {
                    replicate: 'mean',
                    rawTPM: 519.45,
                    logTPM: 9.02,
                    rawFPKM: 1161.685,
                    logFPKM: 10.18,
                    rID: ',',
                },
            ],
        },
        {
            tissue: 'blood',
            cellType: 'K562',
            expID: 'ENCSR384ZXD',
            ageTitle: '',
            gene_name: 'PTMA',
            ensemblid_ver: 'ENSG00000187514.10',
            reps: [
                {
                    replicate: 1,
                    rawTPM: 1806.29,
                    logTPM: 10.82,
                    rawFPKM: 2245.66,
                    logFPKM: 11.13,
                },
                {
                    replicate: 2,
                    rawTPM: 1586.37,
                    logTPM: 10.63,
                    rawFPKM: 2077.06,
                    logFPKM: 11.02,
                },
                {
                    replicate: 'mean',
                    rawTPM: 1696.33,
                    logTPM: 10.73,
                    rawFPKM: 2161.3599999999997,
                    logFPKM: 11.08,
                    rID: ',',
                },
            ],
        },
    ];

    afterEach(() => {
        jest.resetAllMocks();
    });

    it('returns data by gene', async () => {
        jest.spyOn(db, 'any').mockResolvedValue(data_expression);
        const spy = jest.spyOn(db_geneexp, 'geneexp_bygene');
        const result = await db_geneexp.geneexp('hg19', 'PTMA', undefined, undefined, [], [], false, true, true);
        expect(spy).toBeCalled();
        expect(result).toEqual(expression_result);
    });

    it('returns data by experiment', async () => {
        jest.spyOn(db, 'any').mockResolvedValue(data_expression);
        const spy = jest.spyOn(db_geneexp, 'geneexp_byexperiment');
        const result = await db_geneexp.geneexp('hg19', undefined, undefined, 'ENCSR000000', [], [], false, true, true);
        expect(spy).toBeCalled();
        expect(result).toEqual(expression_result);
    });

    it('returns data by biosample', async () => {
        jest.spyOn(db, 'any').mockResolvedValue(data_expression);
        const spy = jest.spyOn(db_geneexp, 'geneexp_bybiosample');
        const result = await db_geneexp.geneexp('hg19', undefined, 'K562', undefined, [], [], false, true, true);
        expect(spy).toBeCalled();
        expect(result).toEqual(expression_result);
    });
});
